_G.GUILD_BANK = 'Guild Bank'
_G.STAT_AVERAGE_ITEM_LEVEL_EQUIPPED = '(Equipped %d)'
_G.BANK = 'Bank'
_G.REAGENT_BANK = 'Reagent bank'
_G.BAGSLOT = 'Bag'
_G.VOID_STORAGE = 'Void Storage'
_G.MAIL_LABEL = 'Mail'